"""Meteora Dynamic Bonding Curve account and event layouts (master §7).

Generated from the official IDL (MeteoraAg dynamic-bonding-curve-sdk 1.5.13, program
dbcij3LWUppWqq96dh6gJWwBifmcGfLSB5D4DuSMaqN, IDL version 0.2.1): only the types the read
path needs. Types are (field name, type); a type is a primitive name, a
struct name, or [element type, length] for a fixed array. Do not edit by
hand: regenerate from the IDL when the program changes."""

PROGRAM_ID = "dbcij3LWUppWqq96dh6gJWwBifmcGfLSB5D4DuSMaqN"
IDL_VERSION = "0.2.1"
ACCOUNT_DISCRIMINATORS = {'PoolConfig': [26, 108, 14, 123, 116, 230, 129, 43], 'VirtualPool': [213, 224, 5, 209, 98, 69, 119, 92]}
EVENT_DISCRIMINATORS = {'EvtSwap': [27, 60, 21, 213, 138, 170, 187, 147], 'EvtSwap2': [189, 66, 51, 168, 38, 80, 117, 153]}
TYPES: dict[str, list] = {'BaseFeeConfig': [('cliff_fee_numerator', 'u64'),
                   ('second_factor', 'u64'),
                   ('third_factor', 'u64'),
                   ('first_factor', 'u16'),
                   ('base_fee_mode', 'u8'),
                   ('padding_0', ['u8', 5])],
 'DynamicFeeConfig': [('initialized', 'u8'),
                      ('padding', ['u8', 7]),
                      ('max_volatility_accumulator', 'u32'),
                      ('variable_fee_control', 'u32'),
                      ('bin_step', 'u16'),
                      ('filter_period', 'u16'),
                      ('decay_period', 'u16'),
                      ('reduction_factor', 'u16'),
                      ('padding2', ['u8', 8]),
                      ('bin_step_u128', 'u128')],
 'EvtSwap': [('pool', 'pubkey'),
             ('config', 'pubkey'),
             ('trade_direction', 'u8'),
             ('has_referral', 'bool'),
             ('params', 'SwapParameters'),
             ('swap_result', 'SwapResult'),
             ('amount_in', 'u64'),
             ('current_timestamp', 'u64')],
 'EvtSwap2': [('pool', 'pubkey'),
              ('config', 'pubkey'),
              ('trade_direction', 'u8'),
              ('has_referral', 'bool'),
              ('swap_parameters', 'SwapParameters2'),
              ('swap_result', 'SwapResult2'),
              ('quote_reserve_amount', 'u64'),
              ('migration_threshold', 'u64'),
              ('current_timestamp', 'u64')],
 'LiquidityDistributionConfig': [('sqrt_price', 'u128'), ('liquidity', 'u128')],
 'LiquidityVestingInfo': [('is_initialized', 'u8'),
                          ('vesting_percentage', 'u8'),
                          ('_padding', ['u8', 2]),
                          ('bps_per_period', 'u16'),
                          ('number_of_periods', 'u16'),
                          ('frequency', 'u32'),
                          ('cliff_duration_from_migration_time', 'u32')],
 'LockedVestingConfig': [('amount_per_period', 'u64'),
                         ('cliff_duration_from_migration_time', 'u64'),
                         ('frequency', 'u64'),
                         ('number_of_period', 'u64'),
                         ('cliff_unlock_amount', 'u64'),
                         ('_padding', 'u64')],
 'PoolConfig': [('quote_mint', 'pubkey'),
                ('fee_claimer', 'pubkey'),
                ('leftover_receiver', 'pubkey'),
                ('pool_fees', 'PoolFeesConfig'),
                ('partner_liquidity_vesting_info', 'LiquidityVestingInfo'),
                ('creator_liquidity_vesting_info', 'LiquidityVestingInfo'),
                ('padding_0', ['u8', 14]),
                ('padding_1', 'u16'),
                ('collect_fee_mode', 'u8'),
                ('migration_option', 'u8'),
                ('activation_type', 'u8'),
                ('token_decimal', 'u8'),
                ('version', 'u8'),
                ('token_type', 'u8'),
                ('quote_token_flag', 'u8'),
                ('partner_permanent_locked_liquidity_percentage', 'u8'),
                ('partner_liquidity_percentage', 'u8'),
                ('creator_permanent_locked_liquidity_percentage', 'u8'),
                ('creator_liquidity_percentage', 'u8'),
                ('migration_fee_option', 'u8'),
                ('fixed_token_supply_flag', 'u8'),
                ('creator_trading_fee_percentage', 'u8'),
                ('token_update_authority', 'u8'),
                ('migration_fee_percentage', 'u8'),
                ('creator_migration_fee_percentage', 'u8'),
                ('padding_2', ['u8', 7]),
                ('swap_base_amount', 'u64'),
                ('migration_quote_threshold', 'u64'),
                ('migration_base_threshold', 'u64'),
                ('migration_sqrt_price', 'u128'),
                ('locked_vesting_config', 'LockedVestingConfig'),
                ('pre_migration_token_supply', 'u64'),
                ('post_migration_token_supply', 'u64'),
                ('migrated_collect_fee_mode', 'u8'),
                ('migrated_dynamic_fee', 'u8'),
                ('migrated_pool_fee_bps', 'u16'),
                ('migrated_pool_base_fee_mode', 'u8'),
                ('enable_first_swap_with_min_fee', 'u8'),
                ('migrated_compounding_fee_bps', 'u16'),
                ('pool_creation_fee', 'u64'),
                ('migrated_pool_base_fee_bytes', ['u8', 16]),
                ('sqrt_start_price', 'u128'),
                ('curve', ['LiquidityDistributionConfig', 20])],
 'PoolFeesConfig': [('base_fee', 'BaseFeeConfig'), ('dynamic_fee', 'DynamicFeeConfig')],
 'PoolMetrics': [('total_protocol_base_fee', 'u64'),
                 ('total_protocol_quote_fee', 'u64'),
                 ('total_trading_base_fee', 'u64'),
                 ('total_trading_quote_fee', 'u64')],
 'PoolState': [('volatility_tracker', 'VolatilityTracker'),
               ('config', 'pubkey'),
               ('creator', 'pubkey'),
               ('base_mint', 'pubkey'),
               ('base_vault', 'pubkey'),
               ('quote_vault', 'pubkey'),
               ('base_reserve', 'u64'),
               ('quote_reserve', 'u64'),
               ('protocol_base_fee', 'u64'),
               ('protocol_quote_fee', 'u64'),
               ('partner_base_fee', 'u64'),
               ('partner_quote_fee', 'u64'),
               ('sqrt_price', 'u128'),
               ('activation_point', 'u64'),
               ('pool_type', 'u8'),
               ('is_migrated', 'u8'),
               ('is_partner_withdraw_surplus', 'u8'),
               ('is_protocol_withdraw_surplus', 'u8'),
               ('migration_progress', 'u8'),
               ('is_withdraw_leftover', 'u8'),
               ('is_creator_withdraw_surplus', 'u8'),
               ('migration_fee_withdraw_status', 'u8'),
               ('metrics', 'PoolMetrics'),
               ('finish_curve_timestamp', 'u64'),
               ('creator_base_fee', 'u64'),
               ('creator_quote_fee', 'u64'),
               ('legacy_creation_fee_bits', 'u8'),
               ('creation_fee_bits', 'u8'),
               ('has_swap', 'u8'),
               ('_padding_0', ['u8', 5]),
               ('protocol_liquidity_migration_fee_bps', 'u16'),
               ('_padding_1', ['u8', 6]),
               ('protocol_migration_base_fee_amount', 'u64'),
               ('protocol_migration_quote_fee_amount', 'u64'),
               ('_padding_2', ['u64', 3])],
 'SwapParameters': [('amount_in', 'u64'), ('minimum_amount_out', 'u64')],
 'SwapParameters2': [('amount_0', 'u64'), ('amount_1', 'u64'), ('swap_mode', 'u8')],
 'SwapResult': [('actual_input_amount', 'u64'),
                ('output_amount', 'u64'),
                ('next_sqrt_price', 'u128'),
                ('trading_fee', 'u64'),
                ('protocol_fee', 'u64'),
                ('referral_fee', 'u64')],
 'SwapResult2': [('included_fee_input_amount', 'u64'),
                 ('excluded_fee_input_amount', 'u64'),
                 ('amount_left', 'u64'),
                 ('output_amount', 'u64'),
                 ('next_sqrt_price', 'u128'),
                 ('trading_fee', 'u64'),
                 ('protocol_fee', 'u64'),
                 ('referral_fee', 'u64')],
 'VirtualPool': [('pool_state', 'PoolState')],
 'VolatilityTracker': [('last_update_timestamp', 'u64'),
                       ('padding', ['u8', 8]),
                       ('sqrt_price_reference', 'u128'),
                       ('volatility_accumulator', 'u128'),
                       ('volatility_reference', 'u128')]}
