"""Raydium LaunchLab account and event layouts (master §7).

Generated from the official IDL (raydium-io/raydium-idl raydium_launchpad.json,
program LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj, IDL version 0.2.0): only
the types the read path needs. Types are (field name, type); a type is a
primitive name, a struct name, or [element type, length] for a fixed array;
field-less enums (TradeDirection, PoolStatus, AmmCreatorFeeOn) are u8, and
PlatformConfig is decoded up to its trailing variable-length curve_params
(not needed for a quote). Do not edit by hand:
regenerate from the IDL when the program changes."""

PROGRAM_ID = "LanMV9sAd7wArD4vJFi2qDdfnVhFxYSUg6eADduJ3uj"
IDL_VERSION = "0.2.0"
ACCOUNT_DISCRIMINATORS = {'GlobalConfig': [149, 8, 156, 202, 160, 252, 176, 217], 'PlatformConfig': [160, 78, 128, 0, 248, 83, 230, 160], 'PoolState': [247, 237, 227, 245, 215, 195, 222, 70]}
EVENT_DISCRIMINATORS = {'TradeEvent': [189, 219, 127, 211, 78, 230, 97, 238]}
TYPES: dict[str, list] = {'GlobalConfig': [('epoch', 'u64'),
                  ('curve_type', 'u8'),
                  ('index', 'u16'),
                  ('migrate_fee', 'u64'),
                  ('trade_fee_rate', 'u64'),
                  ('max_share_fee_rate', 'u64'),
                  ('min_base_supply', 'u64'),
                  ('max_lock_rate', 'u64'),
                  ('min_base_sell_rate', 'u64'),
                  ('min_base_migrate_rate', 'u64'),
                  ('min_quote_fund_raising', 'u64'),
                  ('quote_mint', 'pubkey'),
                  ('protocol_fee_owner', 'pubkey'),
                  ('migrate_fee_owner', 'pubkey'),
                  ('migrate_to_amm_wallet', 'pubkey'),
                  ('migrate_to_cpswap_wallet', 'pubkey'),
                  ('requires_platform_auth', 'u8'),
                  ('padding_alignment', ['u8', 7]),
                  ('padding', ['u64', 15])],
 'PlatformConfig': [('epoch', 'u64'),
                    ('platform_fee_wallet', 'pubkey'),
                    ('platform_nft_wallet', 'pubkey'),
                    ('platform_scale', 'u64'),
                    ('creator_scale', 'u64'),
                    ('burn_scale', 'u64'),
                    ('fee_rate', 'u64'),
                    ('name', ['u8', 64]),
                    ('web', ['u8', 256]),
                    ('img', ['u8', 256]),
                    ('cpswap_config', 'pubkey'),
                    ('creator_fee_rate', 'u64'),
                    ('transfer_fee_extension_auth', 'pubkey'),
                    ('platform_vesting_wallet', 'pubkey'),
                    ('platform_vesting_scale', 'u64'),
                    ('platform_cp_creator', 'pubkey'),
                    ('padding', ['u8', 108])],
 'PoolState': [('epoch', 'u64'),
               ('auth_bump', 'u8'),
               ('status', 'u8'),
               ('base_decimals', 'u8'),
               ('quote_decimals', 'u8'),
               ('migrate_type', 'u8'),
               ('supply', 'u64'),
               ('total_base_sell', 'u64'),
               ('virtual_base', 'u64'),
               ('virtual_quote', 'u64'),
               ('real_base', 'u64'),
               ('real_quote', 'u64'),
               ('total_quote_fund_raising', 'u64'),
               ('quote_protocol_fee', 'u64'),
               ('platform_fee', 'u64'),
               ('migrate_fee', 'u64'),
               ('vesting_schedule', 'VestingSchedule'),
               ('global_config', 'pubkey'),
               ('platform_config', 'pubkey'),
               ('base_mint', 'pubkey'),
               ('quote_mint', 'pubkey'),
               ('base_vault', 'pubkey'),
               ('quote_vault', 'pubkey'),
               ('creator', 'pubkey'),
               ('token_program_flag', 'u8'),
               ('amm_creator_fee_on', 'u8'),
               ('platform_vesting_share', 'u64'),
               ('padding', ['u8', 54])],
 'TradeEvent': [('pool_state', 'pubkey'),
                ('total_base_sell', 'u64'),
                ('virtual_base', 'u64'),
                ('virtual_quote', 'u64'),
                ('real_base_before', 'u64'),
                ('real_quote_before', 'u64'),
                ('real_base_after', 'u64'),
                ('real_quote_after', 'u64'),
                ('amount_in', 'u64'),
                ('amount_out', 'u64'),
                ('protocol_fee', 'u64'),
                ('platform_fee', 'u64'),
                ('creator_fee', 'u64'),
                ('share_fee', 'u64'),
                ('trade_direction', 'u8'),
                ('pool_status', 'u8'),
                ('exact_in', 'bool')],
 'VestingSchedule': [('total_locked_amount', 'u64'),
                     ('cliff_period', 'u64'),
                     ('unlock_period', 'u64'),
                     ('start_time', 'u64'),
                     ('allocated_share_amount', 'u64')]}
