"""phase 2 normalized market event storage

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-21

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('snapshot_type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('volume', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('sequence', sa.BigInteger(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'symbol', 'snapshot_type', 'sequence', name='uq_market_snapshots_dedup')
    )
    op.create_index(op.f('ix_market_snapshots_occurred_at'), 'market_snapshots', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_market_snapshots_snapshot_type'), 'market_snapshots', ['snapshot_type'], unique=False)
    op.create_index(op.f('ix_market_snapshots_source'), 'market_snapshots', ['source'], unique=False)
    op.create_index(op.f('ix_market_snapshots_symbol'), 'market_snapshots', ['symbol'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mint_address', sa.String(length=64), nullable=False),
    sa.Column('creator_address', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('metadata_uri', sa.String(length=512), nullable=True),
    sa.Column('first_seen_source', sa.String(length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_creator_address'), 'tokens', ['creator_address'], unique=False)
    op.create_index(op.f('ix_tokens_mint_address'), 'tokens', ['mint_address'], unique=True)
    op.create_table('token_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.Column('trader_address', sa.String(length=64), nullable=True),
    sa.Column('sol_amount', sa.Numeric(precision=24, scale=9), nullable=True),
    sa.Column('token_amount', sa.Numeric(precision=38, scale=0), nullable=True),
    sa.Column('is_buy', sa.Boolean(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'signature', 'event_type', name='uq_token_events_source_signature_type')
    )
    op.create_index(op.f('ix_token_events_event_type'), 'token_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_token_events_occurred_at'), 'token_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_token_events_signature'), 'token_events', ['signature'], unique=False)
    op.create_index(op.f('ix_token_events_token_id'), 'token_events', ['token_id'], unique=False)
    op.create_index(op.f('ix_token_events_trader_address'), 'token_events', ['trader_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_events_trader_address'), table_name='token_events')
    op.drop_index(op.f('ix_token_events_token_id'), table_name='token_events')
    op.drop_index(op.f('ix_token_events_signature'), table_name='token_events')
    op.drop_index(op.f('ix_token_events_occurred_at'), table_name='token_events')
    op.drop_index(op.f('ix_token_events_event_type'), table_name='token_events')
    op.drop_table('token_events')
    op.drop_index(op.f('ix_tokens_mint_address'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_creator_address'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_market_snapshots_symbol'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_source'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_snapshot_type'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_occurred_at'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    # ### end Alembic commands ###
