"""phase 3 trading candidates

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-21

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('state_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_candidates_engine'), 'trading_candidates', ['engine'], unique=False)
    op.create_index(op.f('ix_trading_candidates_state'), 'trading_candidates', ['state'], unique=False)
    op.create_index(op.f('ix_trading_candidates_token_id'), 'trading_candidates', ['token_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_candidates_token_id'), table_name='trading_candidates')
    op.drop_index(op.f('ix_trading_candidates_state'), table_name='trading_candidates')
    op.drop_index(op.f('ix_trading_candidates_engine'), table_name='trading_candidates')
    op.drop_table('trading_candidates')
    # ### end Alembic commands ###
