"""phase 4 binance futures execution state

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-22

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_order_id', sa.String(length=36), nullable=False),
    sa.Column('exchange_order_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('position_side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=24), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('reduce_only', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_client_order_id'), 'orders', ['client_order_id'], unique=True)
    op.create_index(op.f('ix_orders_exchange_order_id'), 'orders', ['exchange_order_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('pnl_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('income_type', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('income', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('asset', sa.String(length=16), nullable=False),
    sa.Column('tran_id', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pnl_records_income_type'), 'pnl_records', ['income_type'], unique=False)
    op.create_index(op.f('ix_pnl_records_occurred_at'), 'pnl_records', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_pnl_records_symbol'), 'pnl_records', ['symbol'], unique=False)
    op.create_index(op.f('ix_pnl_records_tran_id'), 'pnl_records', ['tran_id'], unique=True)
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('position_amt', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('mark_price', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.Column('margin_type', sa.String(length=16), nullable=True),
    sa.Column('liquidation_price', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=True)
    op.create_table('fills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('exchange_trade_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('commission', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('commission_asset', sa.String(length=16), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fills_exchange_trade_id'), 'fills', ['exchange_trade_id'], unique=True)
    op.create_index(op.f('ix_fills_occurred_at'), 'fills', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_fills_order_id'), 'fills', ['order_id'], unique=False)
    op.create_index(op.f('ix_fills_symbol'), 'fills', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fills_symbol'), table_name='fills')
    op.drop_index(op.f('ix_fills_order_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_occurred_at'), table_name='fills')
    op.drop_index(op.f('ix_fills_exchange_trade_id'), table_name='fills')
    op.drop_table('fills')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_pnl_records_tran_id'), table_name='pnl_records')
    op.drop_index(op.f('ix_pnl_records_symbol'), table_name='pnl_records')
    op.drop_index(op.f('ix_pnl_records_occurred_at'), table_name='pnl_records')
    op.drop_index(op.f('ix_pnl_records_income_type'), table_name='pnl_records')
    op.drop_table('pnl_records')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_exchange_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_order_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
