"""phase 5 shared decision system

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-22

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['trading_candidates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_approved'), 'risk_events', ['approved'], unique=False)
    op.create_index(op.f('ix_risk_events_candidate_id'), 'risk_events', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_risk_events_created_at'), 'risk_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_events_symbol'), 'risk_events', ['symbol'], unique=False)
    op.create_table('strategy_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('entry_type', sa.String(length=16), nullable=True),
    sa.Column('entry', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('take_profit', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('reason', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_quality', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['trading_candidates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_signals_candidate_id'), 'strategy_signals', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_strategy_signals_created_at'), 'strategy_signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategy_signals_decision'), 'strategy_signals', ['decision'], unique=False)
    op.create_index(op.f('ix_strategy_signals_symbol'), 'strategy_signals', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_signals_symbol'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_decision'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_created_at'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_candidate_id'), table_name='strategy_signals')
    op.drop_table('strategy_signals')
    op.drop_index(op.f('ix_risk_events_symbol'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_created_at'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_candidate_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_approved'), table_name='risk_events')
    op.drop_table('risk_events')
    # ### end Alembic commands ###
