"""phase 6 ml model registry and feature store

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-22 00:41:05.632111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('feature_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('training_sample_count', sa.Integer(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifact', sa.LargeBinary(), nullable=False),
    sa.Column('artifact_format', sa.String(length=16), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_versions_name_version')
    )
    op.create_index(op.f('ix_model_versions_name'), 'model_versions', ['name'], unique=False)
    op.create_index(op.f('ix_model_versions_status'), 'model_versions', ['status'], unique=False)
    op.create_table('ml_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=True),
    sa.Column('ml_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('label', sa.Integer(), nullable=True),
    sa.Column('label_source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['trading_candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_features_candidate_id'), 'ml_features', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_ml_features_created_at'), 'ml_features', ['created_at'], unique=False)
    op.create_index(op.f('ix_ml_features_label'), 'ml_features', ['label'], unique=False)
    op.create_index(op.f('ix_ml_features_model_version_id'), 'ml_features', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_ml_features_symbol'), 'ml_features', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_features_symbol'), table_name='ml_features')
    op.drop_index(op.f('ix_ml_features_model_version_id'), table_name='ml_features')
    op.drop_index(op.f('ix_ml_features_label'), table_name='ml_features')
    op.drop_index(op.f('ix_ml_features_created_at'), table_name='ml_features')
    op.drop_index(op.f('ix_ml_features_candidate_id'), table_name='ml_features')
    op.drop_table('ml_features')
    op.drop_index(op.f('ix_model_versions_status'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_name'), table_name='model_versions')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
