"""phase 7 paper trading

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-22 00:59:21.564876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0007'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('take_profit', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('exit_reason', sa.String(length=32), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('realized_pnl_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('entry_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['trading_candidates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_positions_candidate_id'), 'paper_positions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_paper_positions_created_at'), 'paper_positions', ['created_at'], unique=False)
    op.create_index(op.f('ix_paper_positions_status'), 'paper_positions', ['status'], unique=False)
    op.create_index(op.f('ix_paper_positions_symbol'), 'paper_positions', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_positions_symbol'), table_name='paper_positions')
    op.drop_index(op.f('ix_paper_positions_status'), table_name='paper_positions')
    op.drop_index(op.f('ix_paper_positions_created_at'), table_name='paper_positions')
    op.drop_index(op.f('ix_paper_positions_candidate_id'), table_name='paper_positions')
    op.drop_table('paper_positions')
    # ### end Alembic commands ###
