"""control center: runtime risk settings, operator rules, persisted safety
assessments, paper accounts and gate-driven paper position fields

Adds only tables and nullable columns, so existing rows stay valid and the
upgrade needs no data backfill. Configuration here is non-secret; the
TRADING_ENABLED / LIVE_TRADING_ENABLED / PAPER_TRADING environment flags
remain the outer bound on what any stored mode can do.

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-25 02:10:00.617204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0009'
down_revision: Union[str, None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('quote_currency', sa.String(length=16), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('reset_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('starting_balance > 0', name='ck_paper_accounts_starting_balance_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('blacklist_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('field', sa.String(length=16), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'field', 'match_type', 'value', name='uq_blacklist_rules_identity')
    )
    op.create_index(op.f('ix_blacklist_rules_scope'), 'blacklist_rules', ['scope'], unique=False)
    op.create_table('custom_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('op', sa.String(length=4), nullable=False),
    sa.Column('threshold', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_rules_scope'), 'custom_rules', ['scope'], unique=False)
    op.create_table('platform_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('risk_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'version', name='uq_risk_settings_scope_version')
    )
    op.create_index(op.f('ix_risk_settings_scope'), 'risk_settings', ['scope'], unique=False)
    op.create_table('strategy_configs',
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode IN ('OFF','PAPER','MANUAL','AUTO')", name='ck_strategy_configs_mode'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('strategy')
    )
    op.create_table('risk_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('status_label', sa.String(length=64), nullable=False),
    sa.Column('executable', sa.Boolean(), nullable=False),
    sa.Column('execution_target', sa.String(length=8), nullable=False),
    sa.Column('overall_risk', sa.String(length=16), nullable=False),
    sa.Column('risk_engine_version', sa.String(length=16), nullable=False),
    sa.Column('assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approval_state', sa.String(length=16), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("approval_state IN ('NONE','PENDING','APPROVED','DECLINED','EXPIRED')", name='ck_risk_assessments_approval_state'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['trading_candidates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_risk_assessments_approval_state'), 'risk_assessments', ['approval_state'], unique=False)
    op.create_index(op.f('ix_risk_assessments_asset_id'), 'risk_assessments', ['asset_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_candidate_id'), 'risk_assessments', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_decision'), 'risk_assessments', ['decision'], unique=False)
    op.create_index(op.f('ix_risk_assessments_engine'), 'risk_assessments', ['engine'], unique=False)
    op.create_index(op.f('ix_risk_assessments_evaluated_at'), 'risk_assessments', ['evaluated_at'], unique=False)
    op.create_index(op.f('ix_risk_assessments_executable'), 'risk_assessments', ['executable'], unique=False)
    op.create_table('trade_timeline_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=True),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_id'], ['trading_candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['paper_positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_timeline_events_assessment_id'), 'trade_timeline_events', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_trade_timeline_events_candidate_id'), 'trade_timeline_events', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_trade_timeline_events_occurred_at'), 'trade_timeline_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_trade_timeline_events_position_id'), 'trade_timeline_events', ['position_id'], unique=False)
    op.add_column('paper_positions', sa.Column('account_id', sa.UUID(), nullable=True))
    op.add_column('paper_positions', sa.Column('assessment_id', sa.UUID(), nullable=True))
    op.add_column('paper_positions', sa.Column('engine', sa.String(length=32), nullable=True))
    op.add_column('paper_positions', sa.Column('asset_id', sa.String(length=64), nullable=True))
    op.add_column('paper_positions', sa.Column('initial_quantity', sa.Numeric(precision=38, scale=18), nullable=True))
    op.add_column('paper_positions', sa.Column('remaining_quantity', sa.Numeric(precision=38, scale=18), nullable=True))
    op.add_column('paper_positions', sa.Column('entry_cost_quote', sa.Numeric(precision=38, scale=18), nullable=True))
    op.add_column('paper_positions', sa.Column('proceeds_quote', sa.Numeric(precision=38, scale=18), nullable=True))
    op.add_column('paper_positions', sa.Column('fees_paid_quote', sa.Numeric(precision=38, scale=18), nullable=True))
    op.add_column('paper_positions', sa.Column('max_loss_quote', sa.Numeric(precision=38, scale=18), nullable=True))
    op.add_column('paper_positions', sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('paper_positions', sa.Column('tp_hits', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('paper_positions', sa.Column('trailing_stop', sa.Numeric(precision=38, scale=18), nullable=True))
    op.add_column('paper_positions', sa.Column('highest_price', sa.Numeric(precision=38, scale=18), nullable=True))
    op.add_column('paper_positions', sa.Column('lowest_price', sa.Numeric(precision=38, scale=18), nullable=True))
    op.add_column('paper_positions', sa.Column('last_price', sa.Numeric(precision=38, scale=18), nullable=True))
    op.add_column('paper_positions', sa.Column('last_marked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_paper_positions_account_id'), 'paper_positions', ['account_id'], unique=False)
    op.create_index(op.f('ix_paper_positions_assessment_id'), 'paper_positions', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_paper_positions_asset_id'), 'paper_positions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_paper_positions_engine'), 'paper_positions', ['engine'], unique=False)
    op.create_foreign_key('fk_paper_positions_assessment_id', 'paper_positions', 'risk_assessments', ['assessment_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_paper_positions_account_id', 'paper_positions', 'paper_accounts', ['account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_paper_positions_account_id', 'paper_positions', type_='foreignkey')
    op.drop_constraint('fk_paper_positions_assessment_id', 'paper_positions', type_='foreignkey')
    op.drop_index(op.f('ix_paper_positions_engine'), table_name='paper_positions')
    op.drop_index(op.f('ix_paper_positions_asset_id'), table_name='paper_positions')
    op.drop_index(op.f('ix_paper_positions_assessment_id'), table_name='paper_positions')
    op.drop_index(op.f('ix_paper_positions_account_id'), table_name='paper_positions')
    op.drop_column('paper_positions', 'last_marked_at')
    op.drop_column('paper_positions', 'last_price')
    op.drop_column('paper_positions', 'lowest_price')
    op.drop_column('paper_positions', 'highest_price')
    op.drop_column('paper_positions', 'trailing_stop')
    op.drop_column('paper_positions', 'tp_hits')
    op.drop_column('paper_positions', 'plan')
    op.drop_column('paper_positions', 'max_loss_quote')
    op.drop_column('paper_positions', 'fees_paid_quote')
    op.drop_column('paper_positions', 'proceeds_quote')
    op.drop_column('paper_positions', 'entry_cost_quote')
    op.drop_column('paper_positions', 'remaining_quantity')
    op.drop_column('paper_positions', 'initial_quantity')
    op.drop_column('paper_positions', 'asset_id')
    op.drop_column('paper_positions', 'engine')
    op.drop_column('paper_positions', 'assessment_id')
    op.drop_column('paper_positions', 'account_id')
    op.drop_index(op.f('ix_trade_timeline_events_position_id'), table_name='trade_timeline_events')
    op.drop_index(op.f('ix_trade_timeline_events_occurred_at'), table_name='trade_timeline_events')
    op.drop_index(op.f('ix_trade_timeline_events_candidate_id'), table_name='trade_timeline_events')
    op.drop_index(op.f('ix_trade_timeline_events_assessment_id'), table_name='trade_timeline_events')
    op.drop_table('trade_timeline_events')
    op.drop_index(op.f('ix_risk_assessments_executable'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_evaluated_at'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_engine'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_decision'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_candidate_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_asset_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_approval_state'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_table('strategy_configs')
    op.drop_index(op.f('ix_risk_settings_scope'), table_name='risk_settings')
    op.drop_table('risk_settings')
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_custom_rules_scope'), table_name='custom_rules')
    op.drop_table('custom_rules')
    op.drop_index(op.f('ix_blacklist_rules_scope'), table_name='blacklist_rules')
    op.drop_table('blacklist_rules')
    op.drop_table('paper_accounts')
    # ### end Alembic commands ###
