"""strategies, lifecycle, notifications, ml quality

Adds paper_orders (grid limit orders), strategy_states (durable engine
state), notifications (in-app feed), data_quality_events (ML quarantine),
gate-era ML sample columns, paper position operator controls, the
ANALYZING / WAITING_FOR_* candidate states (state column widened to 32),
and the IGNORED approval state. Additive except the state widening; the
downgrade maps the new state values back to 'observing' before narrowing.

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-25 09:19:44.317692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0010'
down_revision: Union[str, None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('record_type', sa.String(length=32), nullable=False),
    sa.Column('record_id', sa.String(length=64), nullable=False),
    sa.Column('issue', sa.String(length=64), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_events_created_at'), 'data_quality_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_data_quality_events_issue'), 'data_quality_events', ['issue'], unique=False)
    op.create_index(op.f('ix_data_quality_events_record_id'), 'data_quality_events', ['record_id'], unique=False)
    op.create_index(op.f('ix_data_quality_events_source'), 'data_quality_events', ['source'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_kind'), 'notifications', ['kind'], unique=False)
    op.create_index(op.f('ix_notifications_read_at'), 'notifications', ['read_at'], unique=False)
    op.create_table('strategy_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy', 'key', name='uq_strategy_states_strategy_key')
    )
    op.create_index(op.f('ix_strategy_states_strategy'), 'strategy_states', ['strategy'], unique=False)
    op.create_table('paper_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('venue', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('fee', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id')
    )
    op.create_index(op.f('ix_paper_orders_account_id'), 'paper_orders', ['account_id'], unique=False)
    op.create_index(op.f('ix_paper_orders_created_at'), 'paper_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_paper_orders_status'), 'paper_orders', ['status'], unique=False)
    op.create_index(op.f('ix_paper_orders_strategy'), 'paper_orders', ['strategy'], unique=False)
    op.add_column('ml_features', sa.Column('assessment_id', sa.UUID(), nullable=True))
    op.add_column('ml_features', sa.Column('engine', sa.String(length=32), nullable=True))
    op.add_column('ml_features', sa.Column('feature_version', sa.String(length=32), nullable=True))
    op.add_column('ml_features', sa.Column('outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ml_features', sa.Column('quality_status', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_ml_features_assessment_id'), 'ml_features', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_ml_features_engine'), 'ml_features', ['engine'], unique=False)
    op.create_index(op.f('ix_ml_features_quality_status'), 'ml_features', ['quality_status'], unique=False)
    op.create_foreign_key('fk_ml_features_assessment_id', 'ml_features', 'risk_assessments', ['assessment_id'], ['id'], ondelete='SET NULL')
    op.add_column('paper_positions', sa.Column('management_paused', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('paper_positions', sa.Column('exit_requested', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('trading_candidates', 'state',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.drop_constraint("ck_risk_assessments_approval_state", "risk_assessments", type_="check")
    op.create_check_constraint(
        "ck_risk_assessments_approval_state", "risk_assessments",
        "approval_state IN ('NONE','PENDING','APPROVED','DECLINED','EXPIRED','IGNORED')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE risk_assessments SET approval_state = 'EXPIRED' WHERE approval_state = 'IGNORED'")
    op.drop_constraint("ck_risk_assessments_approval_state", "risk_assessments", type_="check")
    op.create_check_constraint(
        "ck_risk_assessments_approval_state", "risk_assessments",
        "approval_state IN ('NONE','PENDING','APPROVED','DECLINED','EXPIRED')",
    )
    op.execute(
        "UPDATE trading_candidates SET state = 'observing' "
        "WHERE state IN ('analyzing', 'waiting_for_liquidity', 'waiting_for_approval')"
    )
    op.alter_column('trading_candidates', 'state',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.drop_column('paper_positions', 'exit_requested')
    op.drop_column('paper_positions', 'management_paused')
    op.drop_constraint('fk_ml_features_assessment_id', 'ml_features', type_='foreignkey')
    op.drop_index(op.f('ix_ml_features_quality_status'), table_name='ml_features')
    op.drop_index(op.f('ix_ml_features_engine'), table_name='ml_features')
    op.drop_index(op.f('ix_ml_features_assessment_id'), table_name='ml_features')
    op.drop_column('ml_features', 'quality_status')
    op.drop_column('ml_features', 'outcome')
    op.drop_column('ml_features', 'feature_version')
    op.drop_column('ml_features', 'engine')
    op.drop_column('ml_features', 'assessment_id')
    op.drop_index(op.f('ix_paper_orders_strategy'), table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_status'), table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_created_at'), table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_account_id'), table_name='paper_orders')
    op.drop_table('paper_orders')
    op.drop_index(op.f('ix_strategy_states_strategy'), table_name='strategy_states')
    op.drop_table('strategy_states')
    op.drop_index(op.f('ix_notifications_read_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_kind'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_data_quality_events_source'), table_name='data_quality_events')
    op.drop_index(op.f('ix_data_quality_events_record_id'), table_name='data_quality_events')
    op.drop_index(op.f('ix_data_quality_events_issue'), table_name='data_quality_events')
    op.drop_index(op.f('ix_data_quality_events_created_at'), table_name='data_quality_events')
    op.drop_table('data_quality_events')
    # ### end Alembic commands ###
