"""live execution orders, reconciliation events, word-filter actions, position provenance

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-25 15:39:26.798390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0011'
down_revision: Union[str, None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('mint', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('route', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.String(length=48), nullable=False),
    sa.Column('amount_kind', sa.String(length=8), nullable=False),
    sa.Column('slippage_pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('priority_fee_sol', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('signature', sa.String(length=100), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('guard', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode IN ('PAPER','LIVE')", name='ck_execution_orders_mode'),
    sa.CheckConstraint("side IN ('BUY','SELL')", name='ck_execution_orders_side'),
    sa.CheckConstraint("status IN ('PENDING','SIGNED','SUBMITTED','CONFIRMED','FAILED','EXPIRED','CANCELLED')", name='ck_execution_orders_status'),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['position_id'], ['paper_positions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_execution_orders_created_at'), 'execution_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_execution_orders_mint'), 'execution_orders', ['mint'], unique=False)
    op.create_index(op.f('ix_execution_orders_position_id'), 'execution_orders', ['position_id'], unique=False)
    op.create_index(op.f('ix_execution_orders_signature'), 'execution_orders', ['signature'], unique=False)
    op.create_index(op.f('ix_execution_orders_status'), 'execution_orders', ['status'], unique=False)
    op.create_table('reconciliation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('mint', sa.String(length=64), nullable=True),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['execution_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['position_id'], ['paper_positions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_events_created_at'), 'reconciliation_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_reconciliation_events_kind'), 'reconciliation_events', ['kind'], unique=False)
    op.add_column('blacklist_rules', sa.Column('action', sa.String(length=8), server_default='BLOCK', nullable=False))
    op.add_column('paper_positions', sa.Column('execution_mode', sa.String(length=8), server_default='PAPER', nullable=False))
    op.add_column('paper_positions', sa.Column('source', sa.String(length=16), nullable=True))
    op.add_column('paper_positions', sa.Column('lifecycle', sa.String(length=16), nullable=True))
    op.add_column('paper_positions', sa.Column('execution_provider', sa.String(length=32), nullable=True))
    op.add_column('paper_positions', sa.Column('execution_route', sa.String(length=32), nullable=True))
    op.add_column('paper_positions', sa.Column('pool', sa.String(length=64), nullable=True))
    op.add_column('paper_positions', sa.Column('strategy', sa.String(length=64), nullable=True))
    op.add_column('paper_positions', sa.Column('model_version', sa.String(length=64), nullable=True))
    op.add_column('paper_positions', sa.Column('feature_version', sa.String(length=32), nullable=True))
    op.add_column('paper_positions', sa.Column('pending_order_id', sa.UUID(), nullable=True))
    op.add_column('paper_positions', sa.Column('exit_failures', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_paper_positions_execution_mode'), 'paper_positions', ['execution_mode'], unique=False)
    # ### end Alembic commands ###
    # A LIVE position is written before its fill (pending_entry, quantity 0).
    op.drop_constraint("ck_paper_positions_quantity_positive", "paper_positions", type_="check")
    op.create_check_constraint("ck_paper_positions_quantity_positive", "paper_positions",
                               "quantity > 0 OR status IN ('pending_entry', 'failed', 'needs_review')")


def downgrade() -> None:
    # Existing zero-quantity LIVE rows are kept: the stricter check applies
    # to new rows only (NOT VALID), rather than deleting history.
    op.drop_constraint("ck_paper_positions_quantity_positive", "paper_positions", type_="check")
    op.execute("ALTER TABLE paper_positions ADD CONSTRAINT ck_paper_positions_quantity_positive "
               "CHECK (quantity > 0) NOT VALID")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_positions_execution_mode'), table_name='paper_positions')
    op.drop_column('paper_positions', 'exit_failures')
    op.drop_column('paper_positions', 'pending_order_id')
    op.drop_column('paper_positions', 'feature_version')
    op.drop_column('paper_positions', 'model_version')
    op.drop_column('paper_positions', 'strategy')
    op.drop_column('paper_positions', 'pool')
    op.drop_column('paper_positions', 'execution_route')
    op.drop_column('paper_positions', 'execution_provider')
    op.drop_column('paper_positions', 'lifecycle')
    op.drop_column('paper_positions', 'source')
    op.drop_column('paper_positions', 'execution_mode')
    # Map word-filter rules back to what 0010-era code understands; anything
    # that can't be expressed is disabled, never deleted.
    op.execute("UPDATE blacklist_rules SET enabled = false WHERE action = 'ALLOW' OR match_type = 'regex' "
               "OR field IN ('metadata', 'any')")
    op.execute("UPDATE blacklist_rules SET match_type = 'pattern', value = '*' || value || '*' "
               "WHERE match_type IN ('word', 'substring')")
    op.execute("UPDATE blacklist_rules SET scope = 'solana_fresh' WHERE scope = 'FRESH'")
    op.execute("UPDATE blacklist_rules SET scope = 'solana_migration' WHERE scope = 'MIGRATED'")
    op.drop_column('blacklist_rules', 'action')
    op.drop_index(op.f('ix_reconciliation_events_kind'), table_name='reconciliation_events')
    op.drop_index(op.f('ix_reconciliation_events_created_at'), table_name='reconciliation_events')
    op.drop_table('reconciliation_events')
    op.drop_index(op.f('ix_execution_orders_status'), table_name='execution_orders')
    op.drop_index(op.f('ix_execution_orders_signature'), table_name='execution_orders')
    op.drop_index(op.f('ix_execution_orders_position_id'), table_name='execution_orders')
    op.drop_index(op.f('ix_execution_orders_mint'), table_name='execution_orders')
    op.drop_index(op.f('ix_execution_orders_created_at'), table_name='execution_orders')
    op.drop_table('execution_orders')
    # ### end Alembic commands ###
